export const SET_CONTACTS = 'SET_CONTACTS';
export const ONCONTACTADD = 'ONCONTACTADD';
export const ONCONTACTDELETE = 'ONCONTACTDELETE';
export const ONSEARCHINPUTCHANGE = 'ONSEARCHINPUTCHANGE';
export const ONEDITID = 'ONEDITID';
export const ONEDITCONTACT = 'ONEDITCONTACT';
export const ONCHANGENAME = 'ONCHANGENAME';
export const ONCHANGEPHONE = 'ONCHANGEPHONE';